name: Deploy to the server

on:
  push:
    branches:
      - master
jobs:
  deploy_dashboard:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update code
        uses: docker/setup-buildx-action@v1

      - name: Run Docker Compose
        run: |
                  docker-compose down
                  docker-compose up -d --build
       
